import { z } from 'zod';

const acquirerSchema = z.object({
    name: z.string(),
    nii: z.string(),
    terminalId: z.string(),
    merchantId: z.string(),
    currBatchNo: z.number(),
    ip: z.string(),
    port: z.number(),
    ipBackup: z.string(),
    portBackup: z.number(),
    sslType: z.string(),
    tleEnabled: z.boolean(),
    tleVersion: z.string(),
    tleNii: z.string(),
    tleKmsNii: z.string(),
    tleVendorId: z.string(),
    tleAcquirerId: z.string(),
    tleKeySetId: z.string(),
    tleTeId: z.string(),
    tleTePin: z.string(),
    tleSensitiveFields: z.string(),
    alipayTerminalId: z.string(),
    alipayMerchantId: z.string(),
    alipayAcquirer: z.string(),
    wechatTerminalId: z.string(),
    wechatMerchantId: z.string(),
    wechatAcquirer: z.string(),
    tag30TerminalId: z.string(),
    tag30MerchantId: z.string(),
    tag30BillerId: z.string(),
    tag30MerchantName: z.string(),
    tag30PartnerCode: z.string(),
    tag30Ref2: z.boolean(),
    qrcsTerminalId: z.string(),
    qrcsMerchantId: z.string(),
    qrcsPartnerCode: z.string(),
    inquiryTimeout: z.number(),
    inquiryRetries: z.number(),
    apiPublicKey: z.string(),
    apiUrl: z.string(),
    hostTimeout: z.number(),
    merchantName: z.string(),
    tpdu: z.string(),
});

export default acquirerSchema;
